FROM mybase
#RUN http_proxy="http://10.24.48.104:8888" && https_proxy="http://10.24.48.104:8888" && export http_proxy  && export https_proxy  && \
RUN yum install -y nodejs
RUN npm install -g grunt-cli
RUN npm install -g vue


#package
#grunt
#gulp
#webpack


#html
#jade change html rule
#vue  recommed
#https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel
#angular react

# js  style    
# fun
# js fun
# class


#css
#less
#sass  change css rule
#scss(sass3)



#js
#jquery.js
#underscore.js
#zepto.js
#backbone.js

#vue

#sea.js
#require.js


#mv vm

# mvc
#view html tpl  
# model
# controller  event
#https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

#state machine
# viewModel    event
#
