nodejs-weba:
  build: ./nodejs
  expose:
    - 80
nodejs-webb:
  build: ./nodejs
  expose:
    - 80
nodejs-webc:
  build: ./nodejs
  expose:
    - 80

haproxy:
        #image: myhaproxy
  build: ./haproxy
  volumes:
     - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  links:
    - nodejs-weba
    - nodejs-webb
    - nodejs-webc
  ports:    
    - "80:80"
      #- "81:81"
      #- "82:82"
      # - "88:88"
      #    - "443:443"
  expose:    
    - "80"
    - "81"
    - "82"
    - "88"
      #- "443"
