nodejs-web:
  build: ./nodejs
  #working_dir: /src
  #command: bash -c "node /src/index.js && /usr/sbin/sshd -D"
  #scale: 5
  expose:
    - 22
    - 80
haproxy:
        #image: myhaproxy
  build: ./haproxy
  volumes:
     - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  links:
    - nodejs-web
  ports:    
    - "80:80"
      #- "81:81"
      #- "82:82"
      # - "88:88"
      #    - "443:443"
  expose:    
    - "22"
    - "80"
    - "81"
    - "82"
    - "88"
      #- "443"
