etcd:
  #image: mywildfly
  build: ./etcd
  #working_dir: /src
  #command: bash -c "node /src/index.js && /usr/sbin/sshd -D"
  #scale: 5
  ports:
    - 2380:2380
    - 7001:7001
    - 2379:2379
    - 4001:4001
  expose:
    - 2380
    - 7001
    - 2379
    - 4001
wildfly:
  image: mywildfly
  #build: ./nodejs
  #working_dir: /src
  #command: bash -c "node /src/index.js && /usr/sbin/sshd -D"
  #scale: 5
  expose:
    - 22
    - 8080
nginx:
  #image: mynginx
  build: ./nginx
  #working_dir: /src
  #command: bash -c "/usr/sbin/nginx -c /etc/nginx/nginx.conf"
  #scale: 5
  volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - wildfly
  #depends_on:
  #  - wildfly
  expose:
    - 22
    - 80
haproxy:
  #image: myhaproxy
  build: ./haproxy
  volumes:
     - /share:/share:rw
       # - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  links:
    - etcd
    - nginx
  ports:    
    - "80:80"
  expose:    
    - "22"
    - "80"
    #- "443"
